version: 2
jobs:
  build_and_test:
    docker:
      - image: ubuntu:18.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      - image: node:latest

    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/ci-test

    steps:
      - checkout
      - run:
            apt-get update -y && apt-get upgrade -y
      - run:
            apt-get install npm -y
            npm -v
      - run: 
            ll
      - run:
            npm install
      - run:
            npm run test
            

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test
