version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  build_and_test:
    docker:
      - image: ubuntu:18.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/ci-test

    steps:
      - checkout
      - run:
            apt-get update -y && apt-get upgrade -y
      - run:
            apt-get install curl -y
      - node/install:
          install-yarn: true
      - run: node --version
      - run:
            npm -v
      - run: 
            ls -al
      - run:
            npm install
      - run:
            npm run test
            

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test
