version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      - image: nodejs:latest

    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/ci-test

    steps:
      - checkout

      - run:
          command: npm run test


workflows:
  version: 2
  build-deploy:
    jobs:
      - build

