version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      - image: node:latest

    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/ci-test

    steps:
      - run:
          command:  |
            apt-get update -y
            apt-get upgrade -y
            apt-get install npm -y
            npm -v
  test:
    steps:
      - run:
          - checkout
          command:
            npm run test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test

