
version: 2
jobs: 
  build:
    steps:
      - checkout # this pulls code down from GitHub
      - run: npm install
  test:
    steps:
      - run: npm run test
workflows:
  version: 2
    ci-start:
    jobs:
      - build
      - test